version: 2.1

orbs:
  node: circleci/node@5.0.2
  gcp-cli: circleci/gcp-cli@2.4.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:0.13.5

jobs:
  npm_install_lint_and_test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          name: npm install - shared/
          command: |
            cd shared
            npm install
      - run:
          name: npm lint - shared/
          command: |
            cd shared
            npm run lint
      - run:
          name: npm test - shared/
          command: |
            cd shared
            npm test
      - run:
          name: npm audit - shared/
          command: |
            cd shared
            npm audit --only=prod
      - run:
          name: npm install - ingestion/batch/
          command: |
            cd ingestion/batch
            npm install
      - run:
          name: npm lint - ingestion/batch/
          command: |
            cd ingestion/batch
            npm run lint
      - run:
          name: npm test - ingestion/batch/
          command: |
            cd ingestion/batch
            npm test
      - run:
          name: npm audit - ingestion/batch/
          command: |
            cd ingestion/batch
            npm audit --only=prod
      - run:
          name: npm install - ingestion/streaming/
          command: |
            cd ingestion/streaming
            npm install
      - run:
          name: npm lint - ingestion/streaming/
          command: |
            cd ingestion/streaming
            npm run lint
      - run:
          name: npm audit - ingestion/streaming/
          command: |
            cd ingestion/streaming
            npm audit --only=prod
      - run:
          name: npm install - api/v1
          command: |
            cd api/v1
            npm install
      - run:
          name: npm lint - api/v1
          command: |
            cd api/v1
            npm run lint
      - run:
          name: npm audit - api/v1
          command: |
            cd api/v1
            npm audit --only=prod
      - run:
          name: npm install - frontend/
          command: |
            cd frontend
            npm install
      - run:
          name: npm lint - frontend/
          command: |
            cd frontend
            npm run lint
#      - run:
#          name: npm audit - frontend/
#          command: |
#            cd frontend
#            npm audit --only=prod

  terraform_plan:
    executor: terraform
    environment:
      TF_LOG: TRACE
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run:
          name: Init Terraform
          command: |
            cd terraform/deploy/env/<< parameters.env >>/
            terraform init \
            -input=false
      - run:
          name: Terraform Plan
          command: |
            echo "Planning infrastructure update..."
            sh terraform/deploy/env/<< parameters.env >>/modules/ingestion-function/scripts/create-cloud-function-zip.sh
            cd terraform/deploy/env/<< parameters.env >>/
            terraform plan \
              -input=false -out="tfplan_<< parameters.env >>"
      - persist_to_workspace:
          root: .
          paths:
            - terraform/deploy/env/<< parameters.env >>

  deploy:
    executor: terraform
    parameters:
      env:
        type: string
      version:
        default: 363.0.0
        description: >-
          Version of the CLI to install. Must contain the full version number as it
          appears in the URL on this page:
          https://cloud.google.com/sdk/docs/downloads-versioned-archives
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install gcloud cli
          command: |
            apk add --update \
            python3 \
            curl \
            which \
            bash
            curl https://sdk.cloud.google.com > install.sh
            bash install.sh --disable-prompts
            export PATH=$PATH:/root/google-cloud-sdk/bin/
            gcloud version
            cd terraform/deploy/env/<< parameters.env >>/
            terraform apply -auto-approve -input=false "tfplan_<< parameters.env >>"


workflows:
  main:
    jobs:
      - npm_install_lint_and_test:
          name: node dependency installation
      - terraform_plan:
          name: staging_plan
          context: staging
          env: staging
      - deploy:
          name: staging_deploy
          context: staging
          env: staging
          requires:
            - staging_plan
##      - terraform_plan:
##          name: production_plan
##          context: production
##          env: production
##          type: approval
##          requires:
##            - staging_deploy
##      - deploy:
##          name: production_deploy
##          context: production
##          env: production
##          requires:
##            - production_plan